name: Deploy
on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.repository == 'jmjuanes/tyler' }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    # Deploy to github pages env
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/configure-pages@v1
      - run: yarn install
      - uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: '.'
      - uses: actions/deploy-pages@v1
        id: deployment
